version: "3"

networks:
  default:
    external: false

volumes:
  influx_data:
  redis_data:
  api_data:

services:
  redis:
    image: redis:6.0.1-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../data/redis:/data
    command: redis-server --appendonly yes
    restart: always
    env_file: [.env]

  api:
    image: dis2020/blockchain-auctions-api
    build: ./
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - influx
      - redis
    env_file: [.env]
    environment:
      INFLUXDB_HOST: influx
      REDIS_HOST: redis
